# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opc <- function(x, mu, sigma, beta, minLen, maxLen) {
    .Call(`_anomalous_opc`, x, mu, sigma, beta, minLen, maxLen)
}

peltc <- function(x, mu, sigma, beta, minLen, maxLen) {
    .Call(`_anomalous_peltc`, x, mu, sigma, beta, minLen, maxLen)
}

